name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
     
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Organzation
      description: Please select your  Organzation
      placeholder: select
      options:
        - CIBC 
        - CIBC EMU
        - Safari
        - Microsoft Edge
    validations:
      required: true
  - type: dropdown
  
