name: Issue Form
description: Capture details from user and create an issue with the details. 
title: "issues:"
labels: ["form" ,"triage"]
#assignees:
# - octocat
body:
- type: markdown 
attributes:
value: |
    Use this form to fill the details.
- type: dropdown
#id: Organization
attributes:
label: Please select your organization. 
options:
- CIBC
- CIBCEMU
validations:
required: true
- type: input
#id: Repositoryname 
attributes:
label: Enter your Application/Repository name 
validations:
required: true
- type: input 
attributes:
label: Enter the MAP ID 
validations:
required: true
- type: textarea
#id: Users 
attributes:
label: Add users
placeholder: "Type or choose the user."
render: github
validations:
required: true
- type: input 
attributes:
label: Select your Repository admin
description: "Select a user from the above user list."
validations:
required: true
